language: java
jdk: oraclejdk8
rvm:
  - 2.2

env:
  global:
    - ARTIFACTS_BUCKET=schema.labs.datacite.org
    - secure: a0a3yKbHDcLo0Igtn+reXVQUBy16X42NCrPMa7i45dF1K+qweiewZTUYvxNJLwZKHCF3Cysoali9K6+mrLisQNLNky1FD1LDXSfBL1ueTel3FYfOnc4DmZvJ0P3mKsCjcbfYe0T8ihfJAy/MFG0/A88d/PXZ0eIj3koHi+unVp8=

before_install:
  - wget http://www.htacg.org/binaries/binaries/tidy-4.9.23/tidy5-4.9.23-32bit.deb
  - sudo dpkg -i tidy5-4.9.23-32bit.deb
  - rm tidy5-4.9.23-32bit.deb

  - wget https://github.com/jgm/pandoc/releases/download/1.15.0.6/pandoc-1.15.0.6-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.0.6-1-amd64.deb
  - rm pandoc-1.15.0.6-1-amd64.deb

install:
  - bundle install

script:
  - mvn -Dtest=ValidationTest,BasicTest test -B
  - bundle exec jekyll build

addons:
  artifacts: true
  s3_region: "us-east-1"
  debug: true
  paths: _site
  permissions: public_read
