language: java
jdk: oraclejdk8

before_install:
  - wget http://www.htacg.org/binaries/binaries/tidy-4.9.35/tidy5-4.9.35-64bit.deb
  - sudo dpkg -i tidy5-4.9.35-64bit.deb
  - tidy -v

deploy:
  provider: s3
  access_key_id:
    secure: OrScYBEfZQN/oJewVeUNH6/lZMCcrqJUW6qHxVfD1g5qnSwXJBObQr+QLRozh6dnYtZOSDl6Xs9aJnbdTK2SxDrOGOPquJmmzT6hA4WSgNBqPLNLguOX0I55/i5fsZ1P+k/XCfB8Ap9RLeG6PcYn0ktQgHI8AmZg69kMpv1kjXc=
  secret_access_key:
    secure: CTYQKf/DneE8tDujAWJ78w+89QDTWEhXhYkXATQvWchgPQbAQ/qdHtVtNUaBQKQHXh+cmXmzhFPt7FLogPFHsefRx2jHjgqtToa1YtaqDcSNdeH74iAuAyPb5nPAGdgMYCglB/MtODRW6vfAJl2/l0Ta7qKr1QKyLoMgI4NdHZE=
  bucket: schema.labs.datacite.org
  endpoint: schema.labs.datacite.org.s3-website-us-east-1.amazonaws.com
  local_dir: www
  acl: public_read
  on:
    repo: datacite/schema
    branch: labs
