language: java
jdk: oraclejdk8
before_install:
- wget http://www.htacg.org/binaries/binaries/tidy-4.9.23/tidy5-4.9.23-32bit.deb
- sudo dpkg -i tidy5-4.9.23-32bit.deb
- rm tidy5-4.9.23-32bit.deb
script: mvn -Dtest=ValidationTest,BasicTest test -B
deploy:
  provider: s3
  access_key_id:
    secure: "Wuoa+4ldUffSQFDko8H99W7R/w5IbItEbdw1hrsxNm2OJwEGAG1nZDOP7MArUXlbKImmY1FsTHWLrcdAiq52skazZMrtlZ3T3YDrAIpUYeyobGL6EM5TjKEIwhkXM95vnhEFiFzWoru9D7XZsnQjvB+7+Ck8Bs+tmSccriKd50c="
  secret_access_key:
    secure: "KI2OlnSmAzvqoRhzoEQjLY9AO77u5lFA97WlcSyDors/83b4oI3xZ5qSj+c1a5pM8CpLDtZkMFR3RJ0h62i1QnyfqZxK0XrefMJSmlSR6mdz5FXqgU+M7EzicA7O0JOlmQEYcX4Sf1xvasqj3ejA3ulzOjdfuKlwe8ktHaWftgk="
  bucket: schema.labs.datacite.org
  local_dir: www
  skip_cleanup: true
  on:
    repo: datacite/schema
    branch: labs
