language: ruby
rvm:
  - 2.2

env:
  global:
    - secure: a0a3yKbHDcLo0Igtn+reXVQUBy16X42NCrPMa7i45dF1K+qweiewZTUYvxNJLwZKHCF3Cysoali9K6+mrLisQNLNky1FD1LDXSfBL1ueTel3FYfOnc4DmZvJ0P3mKsCjcbfYe0T8ihfJAy/MFG0/A88d/PXZ0eIj3koHi+unVp8=

before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.15.0.6/pandoc-1.15.0.6-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.0.6-1-amd64.deb
  - rm pandoc-1.15.0.6-1-amd64.deb

script:
  - bundle exec jekyll build

addons:
  artifacts:
    bucket: schema.labs.datacite.org
    dest: .
    paths: _site
    s3_region: "us-east-1"
    cache_control: "public, max-age=315360000"
    permissions: public_read
