language: java
jdk: oraclejdk8
cache: bundler
cache:
  directories:
    - $HOME/.m2

before_install:
  - set -e
  - if [ "${TRAVIS_TAG?}" ]; then
      AWS_BUCKET="schema.datacite.org";
      RACK_ENV="production";
      cp .env.production .env;
    elif [ "$TRAVIS_BRANCH" == "test" ]; then
      AWS_BUCKET="schema.test.datacite.org";
      RACK_ENV="stage";
      cp .env.test .env;
    else
      exit 1;
    fi
  - rvm install 2.3.1

  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb

install:
  - bundle install

script:
  - bundle exec rspec
  - mvn clean test -B -Droot.dir=build/ -Dindex.html=index.html
  - bundle exec middleman build -e $RACK_ENV

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  local-dir: build
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  detect_encoding: true
  on:
    all_branches: true

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
