language: java
jdk: oraclejdk8
before_install:
- wget http://www.htacg.org/binaries/binaries/tidy-4.9.23/tidy5-4.9.23-32bit.deb
- sudo dpkg -i tidy5-4.9.23-32bit.deb
- rm tidy5-4.9.23-32bit.deb
script: mvn -Dtest=ValidationTest,BasicTest test -B
deploy:
  provider: s3
  access_key_id:
  bucket: schema.labs.datacite.org
  endpoint: schema.labs.datacite.org.s3-website-us-east-1.amazonaws.com
  local_dir: www
  acl: public_read
  on:
    repo: datacite/schema
    branch: labs
env:
  global:
    secure: OR3WAkLKPBAN3Tf4PCDFoAv0MzlfU5h4Uj1vEebLaxiJPP6ZEGa3jYJfRkMrXS6fSXVa220r9gASEwUfcD4DgUf8aUGoIxp+vtNBZRsd8FzrDZiuYDNsupCkvg5h16oMzphK+anJOH97VwqU70aUCMH5CRTY7tA5pVRGiQdU3wY=
