# Build settings
markdown: Pandoc
highlighter: rogue
gems:
  - jekyll-pandoc
  - jemoji

exclude:
  - README.md
  - LICENCE
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - pom.xml
  - src
  - vendor
  - assets/jquery/*

# Site settings
title: "Metadata Schema"

email: support@datacite.org
logo: "/assets/images/logo-small.png"

name: 'DataCite'
author: 'DataCite'
author_image: "/assets/images/author.jpg"

permalink: /:title/

url: "https://schema.datacite.org" # the base hostname & protocol for your site
baseurl: ""
cdn_url: https://assets.datacite.org
#used to display twitter cards
twitter_handle: '@datacite'

#fill in disqus shortname to use disqus
#disqus: datacite

#fill in tracking id
google_analytics: UA-22806196-8

#error tracking
bugsnag: 3708f408208870b6286e92d9d797b1c1

# Build settings
markdown: pandoc
highlighter: pygments
gems:
  - jekyll-pandoc
  - jemoji

exclude:
  - README.md
  - LICENCE
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - vendor
  - assets/jquery/*

pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - number-offset=0
    - csl: _styles/apa.csl
    - bibliography: bibliography/references.bib

